
version: 2

sources:
  - name: acuity_scheduling
    database: prod
    freshness:
      warn_after: {count: 14, period: day}
      error_after: {count: 20, period: day}
    loaded_at_field: "ingested_at"
    schema: raw
    tables:
      - name: appointment_added_event
        description: "Event that indicates appointment creation, configured via Zapier"
      - name: appointment_edited_event
        description: "Event that indicates rescheduling appointment, configured via Zapier"
      - name: appointment_deleted_event
        description: "Event that indicates appointment deletion, configured via Zapier"


models:
  - name: fact_apointment_schedule
    description: "Fact model that represents business process of scheduling appointments"
    columns:
      - name: appointment_id
        description: "Appointment Id"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User first name"
      - name: last_name
        description: "User last name"
      - name: email
        description: "User Email"
      - name: appointment_date
        description: "Date of appointment"
      - name: appointment_time_start
        description: "Time appointment starts/user timezome" 
        meta:
          dimension:
            type: string
      - name: appointment_time_end
        description: "Time appointment ends/user timezome" 
        meta:
          dimension:
            type: string
      - name: appointment_type
        description: "Appointment type: 1-1, Intro Call, Onboarding" 
      - name: calendar_name
        description: "Name of Coach calendar" 
      - name: appointment_created_at
        description: "Date appointment was created" 
      - name: cancelled_flag
        description: "TRUE if appointment was cancelled" 
      - name: appointment_lenght_minutes
        description: "Appointment lenght in minutes" 